ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.plugins.HttpKt.configureHttp
      com.plugins.SerializationKt.configureSerialization
      com.plugins.SecurityKt.configureSecurity
      com.plugins.RoutingKt.configureRouting
    ]
  }
}